# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b5041e12547a979ad94e312bfcfa07981e7349803c5c1592038d6e21803e5cdbc6b4381aa39ef02889ff22e48ff22bac3d6afca66cbb798130e6d39de287fb0

test:
  secret_key_base: 45c09d90eb99a249ea375d509340b00b4d55b02ed724dccd27775dac712bf5c0751cc4048a1e8f85934bd8dc16e42a56b97e0d6ddd057e43e2b361e27bb49a1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
